import { StyleSheet } from 'react-native';
import { COLORS, FONT_SIZES, SIZES, BORDER_RADIUS, SHADOWS } from '../../constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f3f2ef',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  cancelButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  cancelButtonText: {
    fontSize: 16,
    color: '#666666',
    fontWeight: '500',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000000',
    flex: 1,
    textAlign: 'center',
  },
  submitButton: {
    backgroundColor: '#0a66c2',
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 20,
  },
  submitButtonDisabled: {
    backgroundColor: '#e0e0e0',
  },
  submitButtonText: {
    fontSize: 14,
    color: COLORS.white,
    fontWeight: '600',
  },
  submitButtonTextDisabled: {
    color: '#999999',
  },
  content: {
    flex: 1,
    paddingHorizontal: 0,
  },
  section: {
    backgroundColor: COLORS.white,
    marginVertical: 8,
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  typeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginHorizontal: -4,
  },
  typeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#f3f2ef',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#d0d0d0',
    minWidth: '47%',
    marginHorizontal: 4,
  },
  typeButtonSelected: {
    backgroundColor: '#0a66c2',
    borderColor: '#0a66c2',
  },
  typeEmoji: {
    fontSize: 16,
    marginRight: 6,
  },
  typeLabel: {
    fontSize: 13,
    color: '#000000',
    fontWeight: '500',
    flex: 1,
  },
  typeLabelSelected: {
    color: COLORS.white,
    fontWeight: '600',
  },
  titleInput: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d0d0d0',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#000000',
    minHeight: 44,
    fontWeight: '400',
  },
  descriptionInput: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d0d0d0',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    color: '#000000',
    minHeight: 120,
    fontWeight: '400',
    lineHeight: 22,
  },
  characterCount: {
    fontSize: 12,
    color: '#666666',
    marginTop: 8,
    fontWeight: '400',
  },
  previewCard: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: '#d0d0d0',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
  },
  previewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  previewAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#0a66c2',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  previewAvatarText: {
    fontSize: 10,
    color: COLORS.white,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  previewUserInfo: {
    flex: 1,
  },
  previewUserName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
    letterSpacing: 0.1,
  },
  previewTimestamp: {
    fontSize: 12,
    color: '#666666',
    marginTop: 2,
    fontWeight: '400',
  },
  previewType: {
    fontSize: 18,
  },
  previewTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000000',
    marginBottom: 8,
    lineHeight: 22,
    letterSpacing: 0.1,
  },
  previewDescription: {
    fontSize: 14,
    color: '#404040',
    lineHeight: 20,
    fontWeight: '400',
    letterSpacing: 0.1,
  },
});