import { StyleSheet } from 'react-native';
import { COLORS, FONT_SIZES, SIZES, SHADOWS, BORDER_RADIUS } from '../../../constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  safeArea: {
    backgroundColor: COLORS.white,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SIZES.lg,
    paddingVertical: SIZES.md,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    ...SHADOWS.small,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.lightGray + '40',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    fontSize: FONT_SIZES.lg,
    color: COLORS.text,
    fontWeight: '600',
  },
  headerTitle: {
    flex: 1,
    fontSize: FONT_SIZES.lg,
    fontWeight: '700',
    color: COLORS.text,
    textAlign: 'center',
  },
  headerSpacer: {
    width: 44,
  },
  profileHeader: {
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    padding: SIZES.xl,
    alignItems: 'center',
    marginBottom: SIZES.md,
    borderRadius: BORDER_RADIUS.lg,
    ...SHADOWS.small,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  avatarContainer: {
    width: 88,
    height: 88,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.linkedinBlue,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: SIZES.lg,
    borderWidth: 3,
    borderColor: COLORS.linkedinBlue + '20',
  },
  avatarText: {
    fontSize: FONT_SIZES.xxl,
    fontWeight: '700',
    color: COLORS.white,
  },
  profileInfo: {
    flex: 1,
  },
  userName: {
    fontSize: FONT_SIZES.xl,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: SIZES.xs,
  },
  userRole: {
    fontSize: FONT_SIZES.md,
    color: COLORS.linkedinBlue,
    fontWeight: '600',
    marginBottom: SIZES.sm,
    backgroundColor: COLORS.linkedinBlue + '10',
    paddingHorizontal: SIZES.sm,
    paddingVertical: 4,
    borderRadius: BORDER_RADIUS.sm,
    alignSelf: 'flex-start',
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SIZES.sm,
  },
  countryFlag: {
    fontSize: FONT_SIZES.lg,
    marginRight: SIZES.xs,
  },
  locationText: {
    fontSize: FONT_SIZES.md,
    color: COLORS.textSecondary,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  starsContainer: {
    flexDirection: 'row',
    marginRight: SIZES.xs,
  },
  star: {
    fontSize: FONT_SIZES.sm,
  },
  ratingText: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  section: {
    backgroundColor: COLORS.white,
    padding: SIZES.lg,
    marginBottom: SIZES.md,
    borderRadius: BORDER_RADIUS.lg,
    ...SHADOWS.small,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  sectionTitle: {
    fontSize: FONT_SIZES.lg,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: SIZES.md,
  },
  sectionContent: {
    fontSize: FONT_SIZES.md,
    color: COLORS.textSecondary,
    lineHeight: FONT_SIZES.md * 1.5,
    fontWeight: '400',
  },
  bioText: {
    fontSize: FONT_SIZES.md,
    color: COLORS.textSecondary,
    lineHeight: FONT_SIZES.md * 1.6,
    fontWeight: '400',
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SIZES.sm,
  },
  tag: {
    backgroundColor: COLORS.linkedinBlue + '15',
    paddingHorizontal: SIZES.md,
    paddingVertical: SIZES.xs,
    borderRadius: BORDER_RADIUS.round,
    marginRight: SIZES.sm,
    marginBottom: SIZES.sm,
    borderWidth: 1,
    borderColor: COLORS.linkedinBlue + '20',
  },
  styleTag: {
    backgroundColor: COLORS.success + '15',
    borderColor: COLORS.success + '20',
  },
  languageTag: {
    backgroundColor: COLORS.warning + '15',
    borderColor: COLORS.warning + '20',
  },
  timeTag: {
    backgroundColor: COLORS.error + '15',
    borderColor: COLORS.error + '20',
  },
  tagText: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.text,
    fontWeight: '600',
  },
  priceText: {
    fontSize: FONT_SIZES.lg,
    fontWeight: '700',
    color: COLORS.linkedinBlue,
  },
  statsContainer: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    borderRadius: BORDER_RADIUS.lg,
    padding: SIZES.lg,
    marginBottom: SIZES.md,
    justifyContent: 'space-around',
    ...SHADOWS.small,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  statItem: {
    alignItems: 'center',
  },
  statNumber: {
    fontSize: FONT_SIZES.xxl,
    fontWeight: '700',
    color: COLORS.linkedinBlue,
    marginBottom: SIZES.xs,
  },
  statLabel: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.textSecondary,
    textAlign: 'center',
    fontWeight: '500',
  },
  actionContainer: {
    paddingBottom: SIZES.xl,
    gap: SIZES.md,
  },
  primaryButton: {
    backgroundColor: COLORS.linkedinBlue,
    paddingVertical: SIZES.md,
    borderRadius: BORDER_RADIUS.md,
    alignItems: 'center',
    ...SHADOWS.small,
  },
  primaryButtonText: {
    fontSize: FONT_SIZES.md,
    fontWeight: '600',
    color: COLORS.white,
  },
  secondaryButton: {
    backgroundColor: COLORS.white,
    paddingVertical: SIZES.md,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  secondaryButtonText: {
    fontSize: FONT_SIZES.md,
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: SIZES.xl,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: SIZES.lg,
    paddingVertical: SIZES.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  modalTitle: {
    fontSize: FONT_SIZES.xl,
    fontWeight: '700',
    color: COLORS.text,
  },
  modalCloseButton: {
    fontSize: 28,
    color: COLORS.gray,
    fontWeight: '300',
  },
  timeSlotsList: {
    paddingHorizontal: SIZES.lg,
    paddingTop: SIZES.md,
  },
  timeSlotItem: {
    backgroundColor: COLORS.background,
    borderRadius: 12,
    padding: SIZES.md,
    marginBottom: SIZES.sm,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  timeSlotDisabled: {
    backgroundColor: COLORS.lightGray + '30',
    opacity: 0.6,
  },
  timeSlotSelected: {
    backgroundColor: COLORS.primary + '10',
    borderColor: COLORS.primary,
  },
  timeSlotContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  timeSlotDay: {
    fontSize: FONT_SIZES.md,
    fontWeight: '600',
    color: COLORS.text,
  },
  timeSlotTime: {
    fontSize: FONT_SIZES.md,
    color: COLORS.gray,
  },
  timeSlotTextDisabled: {
    color: COLORS.gray + '80',
  },
  timeSlotTextSelected: {
    color: COLORS.primary,
    fontWeight: '700',
  },
  timeSlotUnavailable: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.error,
    marginTop: SIZES.xs,
  },
  modalBookButton: {
    backgroundColor: COLORS.primary,
    marginHorizontal: SIZES.lg,
    marginTop: SIZES.md,
    paddingVertical: SIZES.md,
    borderRadius: 12,
    alignItems: 'center',
    ...SHADOWS.medium,
  },
  modalBookButtonDisabled: {
    backgroundColor: COLORS.gray,
    opacity: 0.5,
  },
  modalBookButtonText: {
    fontSize: FONT_SIZES.md,
    fontWeight: '600',
    color: COLORS.white,
  },
  // Manage Appointments Styles
  addAppointmentForm: {
    padding: SIZES.lg,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  addAppointmentTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: '600',
    color: COLORS.text,
    marginBottom: SIZES.sm,
  },
  appointmentInput: {
    backgroundColor: COLORS.background,
    borderRadius: 8,
    padding: SIZES.md,
    marginBottom: SIZES.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    fontSize: FONT_SIZES.md,
  },
  addAppointmentButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    padding: SIZES.md,
    alignItems: 'center',
  },
  addAppointmentButtonText: {
    fontSize: FONT_SIZES.md,
    fontWeight: '600',
    color: COLORS.white,
  },
  manageSlotItem: {
    backgroundColor: COLORS.background,
    borderRadius: 12,
    padding: SIZES.md,
    marginBottom: SIZES.sm,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  manageSlotContent: {
    flex: 1,
  },
  manageSlotDay: {
    fontSize: FONT_SIZES.md,
    fontWeight: '600',
    color: COLORS.text,
  },
  manageSlotTime: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.gray,
    marginTop: 2,
  },
  manageSlotActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SIZES.xs,
  },
  toggleButton: {
    paddingHorizontal: SIZES.sm,
    paddingVertical: SIZES.xs,
    borderRadius: 6,
  },
  toggleButtonAvailable: {
    backgroundColor: COLORS.success + '20',
  },
  toggleButtonUnavailable: {
    backgroundColor: COLORS.error + '20',
  },
  toggleButtonText: {
    fontSize: FONT_SIZES.xs,
    fontWeight: '600',
    color: COLORS.text,
  },
  deleteButton: {
    padding: SIZES.xs,
  },
  deleteButtonText: {
    fontSize: 20,
  },
});