import { StyleSheet } from 'react-native';
import { COLORS, FONT_SIZES, SIZES, SHADOWS, BORDER_RADIUS } from '../../../constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f3f2ef', // LinkedIn-like background
  },
  smallHeader: {
    backgroundColor: '#ffffff',
    paddingHorizontal: SIZES.lg,
    paddingVertical: SIZES.md,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  helloText: {
    fontSize: FONT_SIZES.lg,
    fontWeight: '600',
    color: COLORS.text,
  },
  content: {
    padding: SIZES.sm,
  },
  header: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 20,
    marginBottom: 8,
    borderRadius: 8,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    borderWidth: 1,
    borderColor: '#d0d0d0',
    marginHorizontal: 12,
  },
  greetingContainer: {
    alignItems: 'center',
    marginBottom: SIZES.md,
  },
  greeting: {
    fontSize: 20,
    fontWeight: '600',
    color: '#0a66c2', // LinkedIn blue
    marginBottom: 6,
    textAlign: 'center',
    letterSpacing: 0.1,
  },
  subtitle: {
    fontSize: 14,
    color: '#666666',
    lineHeight: 20,
    fontWeight: '400',
    textAlign: 'center',
    marginBottom: 8,
  },
  roleIndicator: {
    backgroundColor: '#0077b5',
    paddingHorizontal: SIZES.lg,
    paddingVertical: SIZES.sm,
    borderRadius: BORDER_RADIUS.sm,
    marginTop: SIZES.md,
    alignSelf: 'center',
    minWidth: 120,
  },
  roleText: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.white,
    fontWeight: '600',
    textAlign: 'center',
  },
  section: {
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000000',
    paddingHorizontal: 16,
    paddingVertical: 12,
    letterSpacing: 0.1,
    marginBottom: SIZES.md,
    paddingHorizontal: SIZES.sm,
  },
  quickActions: {
    flexDirection: 'column',
    gap: SIZES.xs,
  },
  actionCard: {
    backgroundColor: COLORS.white,
    padding: SIZES.lg,
    borderRadius: BORDER_RADIUS.sm,
    ...SHADOWS.small,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e1dfdd',
    marginHorizontal: SIZES.xs,
  },
  actionEmoji: {
    fontSize: 24,
    marginRight: SIZES.md,
    backgroundColor: '#f3f2ef',
    padding: SIZES.sm,
    borderRadius: BORDER_RADIUS.round,
    textAlign: 'center',
    minWidth: 48,
    minHeight: 48,
    lineHeight: 32,
  },
  actionTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: '600',
    color: '#000000',
    marginBottom: SIZES.xs,
  },
  actionDescription: {
    fontSize: FONT_SIZES.sm,
    color: '#666666',
    lineHeight: 18,
    fontWeight: '400',
  },
  emptyState: {
    fontSize: FONT_SIZES.md,
    color: '#666666',
    textAlign: 'center',
    fontStyle: 'italic',
    marginTop: SIZES.lg,
  },
  // Feed Board Styles - LinkedIn-like
  feedContainer: {
    backgroundColor: '#f3f2ef',
    paddingVertical: 8,
  },
  feedCard: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    padding: 0,
    marginHorizontal: 12,
    marginBottom: 8,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    borderWidth: 1,
    borderColor: '#d0d0d0',
  },
  feedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
  },
  feedAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#0a66c2',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  feedAvatarText: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  feedUserInfo: {
    flex: 1,
  },
  feedUserName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
    letterSpacing: 0.1,
  },
  clickableUserName: {
    color: '#0a66c2',
    textDecorationLine: 'none',
  },
  feedTimestamp: {
    fontSize: 12,
    color: '#666666',
    marginTop: 2,
    fontWeight: '400',
  },
  feedType: {
    fontSize: 16,
    color: '#666666',
    fontWeight: '400',
  },
  feedContent: {
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  feedTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#000000',
    marginBottom: 8,
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  feedDescription: {
    fontSize: 14,
    color: '#404040',
    lineHeight: 20,
    fontWeight: '400',
    letterSpacing: 0.1,
  },
  feedActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 8,
    paddingHorizontal: 16,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  feedAction: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 4,
    minWidth: 60,
    justifyContent: 'center',
  },
  feedActionText: {
    fontSize: 12,
    color: '#666666',
    marginLeft: 4,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  feedStats: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  feedStatsText: {
    fontSize: 12,
    color: '#666666',
    marginLeft: 4,
    fontWeight: '400',
  },
  // Floating Action Button Styles
  fab: {
    position: 'absolute',
    bottom: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#0a66c2',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  fabIcon: {
    fontSize: 24,
    color: '#ffffff',
  },
  // Loading State Styles
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#666666',
    fontWeight: '400',
  },
  // Empty State Styles
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: 32,
  },
  emptyEmoji: {
    fontSize: 64,
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: COLORS.text,
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 14,
    color: '#666666',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
  },
  emptyButton: {
    backgroundColor: '#0a66c2',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  emptyButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  // Dashboard styles
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  quickActionCard: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  quickActionIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  quickActionText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#333333',
    textAlign: 'center',
  },
  welcomeCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  welcomeTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333333',
    marginBottom: 12,
  },
  welcomeText: {
    fontSize: 14,
    color: '#666666',
    lineHeight: 20,
    marginBottom: 16,
  },
  welcomeButton: {
    backgroundColor: '#0a66c2',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  welcomeButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  subjectsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  subjectCard: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  subjectEmoji: {
    fontSize: 32,
    marginBottom: 8,
  },
  subjectText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#333333',
    textAlign: 'center',
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  statValue: {
    fontSize: 28,
    fontWeight: '700',
    color: '#0a66c2',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#666666',
    textAlign: 'center',
  },
});